# Generated by Django 3.2.12 on 2022-03-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
